[[language]]
name = "rust"
formatter = { command = "rustfmt" , args = ["--edition", "2024"] }

[[language]]
name = "go"
formatter = { command = "gofmt", args = ["-e"] }

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "markdown"
formatter = { command = "mdformat", args = ["-"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--stdin-filepath", ".js"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--stdin-filepath", ".ts"] }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--stdin-filepath", ".html"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--stdin-filepath", ".css"] }

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--stdin-filepath", ".scss"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--stdin-filepath", ".json"] }

